# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

before:
  hooks:
    - go mod tidy
builds:
  - skip: true
dockers:
  - id: go-build
    dockerfile: build/docker/go-build.Dockerfile
    image_templates:
      - atomix/go-build:latest
      - atomix/go-build:{{ .Tag }}
      - atomix/go-build:v{{ .Major }}.{{ .Minor }}
    extra_files:
      - go.mod
  - id: proto-build
    dockerfile: build/docker/proto-build.Dockerfile
    image_templates:
      - atomix/proto-build:latest
      - atomix/proto-build:{{ .Tag }}
      - atomix/proto-build:v{{ .Major }}.{{ .Minor }}
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
