# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

before:
  hooks:
    - go mod tidy
builds:
  - skip: true
dockers:
  - id: runtime-build
    dockerfile: build/docker/runtime-build.Dockerfile
    image_templates:
      - atomix/runtime-build:latest
      - atomix/runtime-build:{{ .Tag }}
      - atomix/runtime-build:v{{ .Major }}.{{ .Minor }}
    extra_files:
      - go.mod
      - go.sum
      - api/
      - cmd/
      - pkg/
  - id: proto-build
    dockerfile: build/docker/proto-build.Dockerfile
    image_templates:
      - atomix/proto-build:latest
      - atomix/proto-build:{{ .Tag }}
      - atomix/proto-build:v{{ .Major }}.{{ .Minor }}
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
