# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - skip: true
dockers:
  - id: go-build
    dockerfile: build/docker/go-build.Dockerfile
    image_templates:
      - atomix/go-build:latest
      - atomix/go-build:{{ .Tag }}
    extra_files:
      - go.mod
  - id: proto-build
    dockerfile: build/docker/proto-build.Dockerfile
    image_templates:
      - atomix/proto-build:latest
      - atomix/proto-build:{{ .Tag }}
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
